baseURL = 'https://onajourney.github.io/'
languageCode = 'en-us'
title = ''
theme = 'papermod'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Notes"
url = "/notes/"
weight = 2

[params.homeInfoParams]
Title = "J. Daniels"
Content = "Curiosities of the mind"
imageUrl = "/avatar.webp"
imageTitle = "My Avatar"
imageWidth = 160
imageHeight = 160

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true

[outputs]
home = ["HTML", "RSS", "JSON"]
